spring:
  profiles:
    default: dev
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: ${CHANGE_LOG}

server:
  port: ${SERVER_PORT}

password:
  length: ${PASSWORD_LENGTH}
bcrypt:
  strength: ${BCRYPT_STRENGTH}
---
spring:
  config:
    activate:
      on-profile: dev
    import: "optional:file:.env-dev[.properties]"
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
---
spring:
  config:
    activate:
      on-profile: prod
    import: "optional:file:.env-prod[.properties]"
